accessWidener	v1	named

# Extra
accessible	field	net/minecraft/server/BiomeStorage	e	I
accessible	field	net/minecraft/server/BiomeStorage	g	[Lnet/minecraft/server/BiomeBase;
accessible	field	net/minecraft/server/DataWatcher	g	Z
accessible	field	net/minecraft/server/EnderDragonBattle	d	Lnet/minecraft/server/WorldServer;
accessible	field	net/minecraft/server/EnderDragonBattle	m	Ljava/util/UUID;
accessible	field	net/minecraft/server/EnderDragonBattle	o	Lnet/minecraft/server/BlockPosition;
accessible	field	net/minecraft/server/EnderDragonBattle	p	Lnet/minecraft/server/EnumDragonRespawn;
accessible	field	net/minecraft/server/EntityBee	cannotEnterHiveTicks	I
accessible	field	net/minecraft/server/EntityInsentient	goalTarget	Lnet/minecraft/server/EntityLiving;
accessible	field	net/minecraft/server/EntityShulkerBullet	shooter	Lnet/minecraft/server/EntityLiving;
accessible	field	net/minecraft/server/EntityShulkerBullet	target	Lnet/minecraft/server/Entity;
accessible	field	net/minecraft/server/ExpirableListEntry	b	Ljava/util/Date;
accessible	field	net/minecraft/server/JsonList	d	Ljava/util/Map;
accessible	field	net/minecraft/server/Raid	raiders	Ljava/util/Map;
accessible	field	net/minecraft/server/TileEntity	position	Lnet/minecraft/server/BlockPosition;
accessible	field	net/minecraft/server/TileEntity	world	Lnet/minecraft/server/World;
accessible	field	net/minecraft/server/WorldNBTStorage	playerDir	Ljava/io/File;
accessible	field	net/minecraft/server/WorldNBTStorage	b	Lorg/apache/logging/log4j/Logger;
accessible	field	net/minecraft/server/WorldNBTStorage	baseDir	Ljava/io/File;

accessible	method	net/minecraft/server/ChunkMapDistance	purgeTickets	()V
accessible	method	net/minecraft/server/DataWatcher	b	(Lnet/minecraft/server/DataWatcherObject;)Lnet/minecraft/server/DataWatcher$Item;
accessible	method	net/minecraft/server/EnderDragonBattle	a	(Lnet/minecraft/server/EnumDragonRespawn;)V
accessible	method	net/minecraft/server/EntityFireballFireball	l	()Lnet/minecraft/server/ItemStack;
accessible	method	net/minecraft/server/EntityInsentient	getDefaultLootTable	()Lnet/minecraft/server/MinecraftKey;
accessible	method	net/minecraft/server/EntityProjectileThrowable	getItem	()Lnet/minecraft/server/ItemStack;
accessible	method	net/minecraft/server/GameRules$GameRuleValue	setValue	(Ljava/lang/String;)V
accessible	method	net/minecraft/server/PlayerChunkMap	unloadChunks	(Ljava/util/function/BooleanSupplier;)V

# CraftBukkit
accessible	class	net/minecraft/server/PlayerChunkMap$EntityTracker
accessible	class	net/minecraft/server/RecipeItemStack$Provider
accessible	class	net/minecraft/server/RecipeItemStack$StackProvider
accessible	class	net/minecraft/server/ItemCooldown$Info
accessible	method	net/minecraft/server/BlockDispenser	dispense	(Lnet/minecraft/server/World;Lnet/minecraft/server/BlockPosition;)V
accessible	method	net/minecraft/server/EntityHanging	setDirection	(Lnet/minecraft/server/EnumDirection;)V
#accessible	method	net/minecraft/server/EntityItemFrame	setDirection	(Lnet/minecraft/server/EnumDirection;)V
accessible	method	net/minecraft/server/EntityLiving	initAttributes	()V
accessible	method	net/minecraft/server/EntitySlime	setSize	(IZ)V
accessible	field	net/minecraft/server/AdvancementDataPlayer	data	Ljava/util/Map;
accessible	field	net/minecraft/server/AdvancementDataWorld	DESERIALIZER	Lcom/google/gson/Gson;
accessible	field	net/minecraft/server/AdvancementDataWorld	REGISTRY	Lnet/minecraft/server/Advancements;
accessible	field	net/minecraft/server/Advancements	advancements	Ljava/util/Map;
accessible	field	net/minecraft/server/AttributeRanged	maximum	D
accessible	field	net/minecraft/server/Block	strength	F
accessible	field	net/minecraft/server/BlockDataAbstract	STATE_TO_VALUE	Ljava/util/function/Function;
accessible	field	net/minecraft/server/BlockDispenser	REGISTRY	Ljava/util/Map;
accessible	method	net/minecraft/server/BlockJukeBox	dropRecord	(Lnet/minecraft/server/World;Lnet/minecraft/server/BlockPosition;)V
accessible	method	net/minecraft/server/BlockRedstoneWire	getPower	(ILnet/minecraft/server/IBlockData;)I
accessible	field	net/minecraft/server/BlockShulkerBox	color	Lnet/minecraft/server/EnumColor;
accessible	field	net/minecraft/server/BossBattle	color	Lnet/minecraft/server/BossBattle$BarColor;
accessible	field	net/minecraft/server/BossBattle	style	Lnet/minecraft/server/BossBattle$BarStyle;
accessible	field	net/minecraft/server/BossBattle	title	Lnet/minecraft/server/IChatBaseComponent;
accessible	method	net/minecraft/server/BossBattleServer	sendUpdate	(Lnet/minecraft/server/PacketPlayOutBoss$Action;)V
accessible	field	net/minecraft/server/BossBattleServer	visible	Z
accessible	field	net/minecraft/server/ChestLock	key	Ljava/lang/String;
accessible	field	net/minecraft/server/Chunk	entitySlices	[Lnet/minecraft/server/EntitySlice;
accessible	field	net/minecraft/server/Chunk	heightMap	Ljava/util/Map;
accessible	field	net/minecraft/server/Chunk	loaded	Z
accessible	field	net/minecraft/server/Chunk	tileEntities	Ljava/util/Map;
accessible	field	net/minecraft/server/Chunk	world	Lnet/minecraft/server/World;
accessible	field	net/minecraft/server/ChunkMapDistance	tickets	Lit/unimi/dsi/fastutil/longs/Long2ObjectOpenHashMap;
accessible	field	net/minecraft/server/ChunkProviderServer	allowAnimals	Z
accessible	field	net/minecraft/server/ChunkProviderServer	allowMonsters	Z
accessible	field	net/minecraft/server/ChunkProviderServer	chunkGenerator	Lnet/minecraft/server/ChunkGenerator;
accessible	field	net/minecraft/server/ChunkSection	GLOBAL_PALETTE	Lnet/minecraft/server/DataPalette;
accessible	field	net/minecraft/server/CommandListenerWrapper	base	Lnet/minecraft/server/ICommandListener;
accessible	field	net/minecraft/server/ContainerAnvil	levelCost	Lnet/minecraft/server/ContainerProperty;
accessible	field	net/minecraft/server/ContainerAnvil	renameText	Ljava/lang/String;
accessible	field	net/minecraft/server/Container	items	Lnet/minecraft/server/NonNullList;
mutable	field	net/minecraft/server/Container	items	Lnet/minecraft/server/NonNullList;
accessible	field	net/minecraft/server/ContainerWorkbench	containerAccess	Lnet/minecraft/server/ContainerAccess;
accessible	method	net/minecraft/server/DataConverterFlattenData	map	(ILjava/lang/String;[Ljava/lang/String;)V
accessible	field	net/minecraft/server/DataConverterMaterialId	ID_MAPPING	Lit/unimi/dsi/fastutil/ints/Int2ObjectMap;
accessible	field	net/minecraft/server/DataConverterSpawnEgg	ID_MAPPING	[Ljava/lang/String;
accessible	field	net/minecraft/server/DedicatedServer	remoteControlCommandListener	Lnet/minecraft/server/RemoteControlCommandListener;
#accessible	method	net/minecraft/server/DimensionManager	<init>	(ILjava/lang/String;Ljava/lang/String;Ljava/util/function/BiFunction;ZLnet/minecraft/server/GenLayerZoomer;)V
accessible	field	net/minecraft/server/DimensionManager	folder	Ljava/lang/String;
accessible	field	net/minecraft/server/DimensionManager	providerFactory	Ljava/util/function/BiFunction;
accessible	method	net/minecraft/server/DimensionManager	register	(Ljava/lang/String;Lnet/minecraft/server/DimensionManager;)Lnet/minecraft/server/DimensionManager;
accessible	field	net/minecraft/server/EnderDragonBattle	bossBattle	Lnet/minecraft/server/BossBattleServer;
accessible	field	net/minecraft/server/Entity	fireTicks	I
accessible	method	net/minecraft/server/Entity	getFlag	(I)Z
accessible	method	net/minecraft/server/Entity	getMaxFireTicks	()I
accessible	method	net/minecraft/server/Entity	getSaveID	()Ljava/lang/String;
accessible	field	net/minecraft/server/Entity	glowing	Z
accessible	field	net/minecraft/server/Entity	inWater	Z
accessible	field	net/minecraft/server/Entity	passengers	Ljava/util/List;
accessible	method	net/minecraft/server/Entity	setFlag	(IZ)V
accessible	field	net/minecraft/server/EntityAnimal	breedCause	Ljava/util/UUID;
accessible	field	net/minecraft/server/EntityAnimal	loveTicks	I
accessible	field	net/minecraft/server/EntityAreaEffectCloud	durationOnUse	I
accessible	field	net/minecraft/server/EntityAreaEffectCloud	radiusOnUse	F
accessible	field	net/minecraft/server/EntityAreaEffectCloud	radiusPerTick	F
accessible	field	net/minecraft/server/EntityAreaEffectCloud	reapplicationDelay	I
accessible	field	net/minecraft/server/EntityAreaEffectCloud	waitTime	I
accessible	field	net/minecraft/server/EntityArmorStand	bodyPose	Lnet/minecraft/server/Vector3f;
accessible	field	net/minecraft/server/EntityArmorStand	headPose	Lnet/minecraft/server/Vector3f;
accessible	field	net/minecraft/server/EntityArmorStand	leftArmPose	Lnet/minecraft/server/Vector3f;
accessible	field	net/minecraft/server/EntityArmorStand	leftLegPose	Lnet/minecraft/server/Vector3f;
accessible	field	net/minecraft/server/EntityArmorStand	rightArmPose	Lnet/minecraft/server/Vector3f;
accessible	field	net/minecraft/server/EntityArmorStand	rightLegPose	Lnet/minecraft/server/Vector3f;
accessible	method	net/minecraft/server/EntityArmorStand	setArms	(Z)V
accessible	method	net/minecraft/server/EntityArmorStand	setBasePlate	(Z)V
accessible	method	net/minecraft/server/EntityArmorStand	setMarker	(Z)V
accessible	method	net/minecraft/server/EntityArmorStand	setSmall	(Z)V
accessible	field	net/minecraft/server/EntityArrow	despawnCounter	I
accessible	field	net/minecraft/server/EntityArrow	inGround	Z
accessible	field	net/minecraft/server/EntityArrow	knockbackStrength	I
accessible	method	net/minecraft/server/EntityBee	getAnger	()I
accessible	field	net/minecraft/server/EntityBee	hivePos	Lnet/minecraft/server/BlockPosition;
accessible	method	net/minecraft/server/EntityBee	setAnger	(I)V
accessible	method	net/minecraft/server/EntityBee	setHasNectar	(Z)V
accessible	method	net/minecraft/server/EntityBee	setHasStung	(Z)V
accessible	method	net/minecraft/server/EntityCreeper	explode	()V
accessible	field	net/minecraft/server/EntityCreeper	explosionRadius	I
accessible	field	net/minecraft/server/EntityCreeper	maxFuseTicks	I
accessible	field	net/minecraft/server/EntityEnderDragon	children	[Lnet/minecraft/server/EntityComplexPart;
accessible	field	net/minecraft/server/EntityEnderSignal	despawnTimer	I
accessible	field	net/minecraft/server/EntityEnderSignal	shouldDropItem	Z
accessible	field	net/minecraft/server/EntityEnderSignal	targetX	D
accessible	field	net/minecraft/server/EntityEnderSignal	targetY	D
accessible	field	net/minecraft/server/EntityEnderSignal	targetZ	D
accessible	field	net/minecraft/server/EntityExperienceOrb	value	I
accessible	field	net/minecraft/server/EntityFallingBlock	hurtEntities	Z
accessible	field	net/minecraft/server/EntityFireworks	FIREWORK_ITEM	Lnet/minecraft/server/DataWatcherObject;
accessible	field	net/minecraft/server/EntityFireworks	SHOT_AT_ANGLE	Lnet/minecraft/server/DataWatcherObject;
accessible	field	net/minecraft/server/EntityFireworks	expectedLifespan	I
accessible	method	net/minecraft/server/EntityFish	isFromBucket	()Z
accessible	field	net/minecraft/server/EntityFox	FIRST_TRUSTED_PLAYER	Lnet/minecraft/server/DataWatcherObject;
accessible	field	net/minecraft/server/EntityFox	SECOND_TRUSTED_PLAYER	Lnet/minecraft/server/DataWatcherObject;
accessible	method	net/minecraft/server/EntityFox	setFoxType	(Lnet/minecraft/server/EntityFox$Type;)V
accessible	method	net/minecraft/server/EntityFox	setSleeping	(Z)V
accessible	field	net/minecraft/server/EntityGuardian	goalRandomStroll	Lnet/minecraft/server/PathfinderGoalRandomStroll;
accessible	field	net/minecraft/server/EntityHanging	blockPosition	Lnet/minecraft/server/BlockPosition;
accessible	field	net/minecraft/server/EntityHorseAbstract	attributeJumpStrength	Lnet/minecraft/server/IAttribute;
accessible	field	net/minecraft/server/EntityHorseAbstract	inventoryChest	Lnet/minecraft/server/InventorySubcontainer;
accessible	method	net/minecraft/server/EntityHorseAbstract	loadChest	()V
accessible	method	net/minecraft/server/EntityHuman	closeInventory	()V
accessible	method	net/minecraft/server/EntityHuman	setShoulderEntityLeft	(Lnet/minecraft/server/NBTTagCompound;)V
accessible	method	net/minecraft/server/EntityHuman	setShoulderEntityRight	(Lnet/minecraft/server/NBTTagCompound;)V
accessible	field	net/minecraft/server/EntityHuman	sleepTicks	I
accessible	method	net/minecraft/server/EntityIllagerWizard	getSpell	()Lnet/minecraft/server/EntityIllagerWizard$Spell;
accessible	field	net/minecraft/server/EntityInsentient	dropChanceArmor	[F
accessible	field	net/minecraft/server/EntityInsentient	dropChanceHand	[F
accessible	field	net/minecraft/server/EntityInsentient	lootTableKey	Lnet/minecraft/server/MinecraftKey;
accessible	field	net/minecraft/server/EntityInsentient	lootTableSeed	J
accessible	field	net/minecraft/server/EntityInsentient	persistent	Z
accessible	field	net/minecraft/server/EntityItem	age	I
accessible	field	net/minecraft/server/EntityItem	pickupDelay	I
accessible	field	net/minecraft/server/EntityLiving	HEALTH	Lnet/minecraft/server/DataWatcherObject;
accessible	field	net/minecraft/server/EntityLiving	effects	Ljava/util/Map;
accessible	field	net/minecraft/server/EntityLiving	hurtTimestamp	I
accessible	field	net/minecraft/server/EntityLiving	killer	Lnet/minecraft/server/EntityHuman;
accessible	field	net/minecraft/server/EntityLiving	lastDamage	F
accessible	field	net/minecraft/server/EntityLiving	lastDamager	Lnet/minecraft/server/EntityLiving;
accessible	field	net/minecraft/server/EntityLiving	updateEffects	Z
accessible	method	net/minecraft/server/EntityLlama	setStrength	(I)V
accessible	field	net/minecraft/server/EntityMinecartCommandBlock	COMMAND	Lnet/minecraft/server/DataWatcherObject;
accessible	field	net/minecraft/server/EntityMinecartContainer	lootTable	Lnet/minecraft/server/MinecraftKey;
accessible	field	net/minecraft/server/EntityMinecartContainer	lootTableSeed	J
accessible	method	net/minecraft/server/EntityMushroomCow	setVariant	(Lnet/minecraft/server/EntityMushroomCow$Type;)V
accessible	field	net/minecraft/server/EntityPigZombie	angerLevel	I
accessible	field	net/minecraft/server/EntityPillager	inventory	Lnet/minecraft/server/InventorySubcontainer;
accessible	field	net/minecraft/server/EntityPlayer	invulnerableTicks	I
accessible	field	net/minecraft/server/EntityPlayer	lastSentExp	I
accessible	field	net/minecraft/server/EntityPlayer	locale	Ljava/lang/String;
accessible	method	net/minecraft/server/EntityPlayer	nextContainerCounter	()V
accessible	field	net/minecraft/server/EntityPlayer	removeQueue	Ljava/util/List;
accessible	method	net/minecraft/server/EntityPlayer	triggerDimensionAdvancements	(Lnet/minecraft/server/WorldServer;)V
accessible	field	net/minecraft/server/EntityPlayer	worldChangeInvuln	Z
accessible	method	net/minecraft/server/EntityPotion	isLingering	()Z
accessible	field	net/minecraft/server/EntityProjectile	shooter	Lnet/minecraft/server/EntityLiving;
accessible	field	net/minecraft/server/EntityProjectile	shooterId	Ljava/util/UUID;
accessible	field	net/minecraft/server/EntityShulker	COLOR	Lnet/minecraft/server/DataWatcherObject;
accessible	field	net/minecraft/server/EntitySpectralArrow	duration	I
accessible	field	net/minecraft/server/EntityThrownTrident	trident	Lnet/minecraft/server/ItemStack;
accessible	field	net/minecraft/server/EntityTippedArrow	effects	Ljava/util/Set;
accessible	method	net/minecraft/server/EntityTippedArrow	setColor	(I)V
accessible	method	net/minecraft/server/EntityVillager	populateTrades	()V
accessible	field	net/minecraft/server/EntityWither	bossBattle	Lnet/minecraft/server/BossBattleServer;
accessible	field	net/minecraft/server/EntityZombie	DROWN_CONVERTING	Lnet/minecraft/server/DataWatcherObject;
accessible	field	net/minecraft/server/EntityZombie	drownedConversionTime	I
accessible	method	net/minecraft/server/EntityZombie	startDrownedConversion	(I)V
accessible	field	net/minecraft/server/EntityZombieVillager	CONVERTING	Lnet/minecraft/server/DataWatcherObject;
accessible	field	net/minecraft/server/EntityZombieVillager	conversionTime	I
accessible	field	net/minecraft/server/EntityZombieVillager	conversionPlayer	Ljava/util/UUID;
accessible	method	net/minecraft/server/EntityZombieVillager	startConversion	(Ljava/util/UUID;I)V
accessible	field	net/minecraft/server/EnumChatFormat	character	C
accessible	field	net/minecraft/server/Explosion	source	Lnet/minecraft/server/Entity;
accessible	field	net/minecraft/server/FoodMetaData	exhaustionLevel	F
accessible	field	net/minecraft/server/FoodMetaData	foodLevel	I
accessible	field	net/minecraft/server/FoodMetaData	saturationLevel	F
accessible	method	net/minecraft/server/GameRules$GameRuleValue	onChange	(Lnet/minecraft/server/MinecraftServer;)V
accessible	field	net/minecraft/server/InventoryCrafting	container	Lnet/minecraft/server/Container;
accessible	field	net/minecraft/server/InventoryLargeChest	left	Lnet/minecraft/server/IInventory;
accessible	field	net/minecraft/server/InventoryLargeChest	right	Lnet/minecraft/server/IInventory;
accessible	field	net/minecraft/server/InventoryMerchant	selectedIndex	I
accessible	field	net/minecraft/server/InventorySubcontainer	items	Lnet/minecraft/server/NonNullList;
accessible	field	net/minecraft/server/ItemBlockWallable	wallBlock	Lnet/minecraft/server/Block;
accessible	field	net/minecraft/server/ItemBucket	fluidType	Lnet/minecraft/server/FluidType;
accessible	field	net/minecraft/server/ItemCooldown$Info	endTick	I
accessible	field	net/minecraft/server/ItemCooldown	cooldowns	Ljava/util/Map;
accessible	field	net/minecraft/server/ItemCooldown	currentTick	I
accessible	method	net/minecraft/server/JsonListEntry	getKey	()Ljava/lang/Object;
accessible	field	net/minecraft/server/MerchantRecipe	priceMultiplier	F
accessible	field	net/minecraft/server/MerchantRecipe	rewardExp	Z
accessible	field	net/minecraft/server/MerchantRecipe	sellingItem	Lnet/minecraft/server/ItemStack;
accessible	field	net/minecraft/server/MerchantRecipe	uses	I
accessible	field	net/minecraft/server/MerchantRecipe	xp	I
accessible	method	net/minecraft/server/MinecraftServer	convertWorld	(Ljava/lang/String;)V
accessible	field	net/minecraft/server/MinecraftServer	dataConverterManager	Lcom/mojang/datafixers/DataFixer;
accessible	field	net/minecraft/server/MinecraftServer	executorService	Ljava/util/concurrent/Executor;
accessible	method	net/minecraft/server/MinecraftServer	loadSpawn	(Lnet/minecraft/server/WorldLoadListener;)V
accessible	field	net/minecraft/server/MinecraftServer	serverThread	Ljava/lang/Thread;
accessible	field	net/minecraft/server/MinecraftServer	worldLoadListenerFactory	Lnet/minecraft/server/WorldLoadListenerFactory;
accessible	field	net/minecraft/server/MinecraftServer	worldServer	Ljava/util/Map;
accessible	method	net/minecraft/server/MobSpawnerAbstract	getMobName	()Lnet/minecraft/server/MinecraftKey;
accessible	field	net/minecraft/server/MobSpawnerAbstract	maxNearbyEntities	I
accessible	field	net/minecraft/server/MobSpawnerAbstract	maxSpawnDelay	I
accessible	field	net/minecraft/server/MobSpawnerAbstract	minSpawnDelay	I
accessible	field	net/minecraft/server/MobSpawnerAbstract	mobs	Ljava/util/List;
accessible	field	net/minecraft/server/MobSpawnerAbstract	requiredPlayerRange	I
accessible	field	net/minecraft/server/MobSpawnerAbstract	spawnCount	I
accessible	field	net/minecraft/server/MobSpawnerAbstract	spawnData	Lnet/minecraft/server/MobSpawnerData;
accessible	field	net/minecraft/server/MobSpawnerAbstract	spawnDelay	I
accessible	field	net/minecraft/server/MobSpawnerAbstract	spawnRange	I
accessible	method	net/minecraft/server/MojangsonParser	parseArray	()Lnet/minecraft/server/NBTBase;
accessible	method	net/minecraft/server/MojangsonParser	parseLiteral	(Ljava/lang/String;)Lnet/minecraft/server/NBTBase;
accessible	field	net/minecraft/server/NetworkManager	channel	Lio/netty/channel/Channel;
accessible	field	net/minecraft/server/NetworkManager	socketAddress	Ljava/net/SocketAddress;
accessible	field	net/minecraft/server/PacketHandshakingInSetProtocol	hostname	Ljava/lang/String;
accessible	field	net/minecraft/server/PacketHandshakingInSetProtocol	port	I
accessible	field	net/minecraft/server/PacketPlayInCustomPayload	data	Lnet/minecraft/server/PacketDataSerializer;
accessible	field	net/minecraft/server/PacketPlayInCustomPayload	tag	Lnet/minecraft/server/MinecraftKey;
accessible	field	net/minecraft/server/PacketPlayInResourcePackStatus	status	Lnet/minecraft/server/PacketPlayInResourcePackStatus$EnumResourcePackStatus;
accessible	field	net/minecraft/server/PacketPlayInSettings	viewDistance	I
accessible	field	net/minecraft/server/PacketPlayOutBlockChange	block	Lnet/minecraft/server/IBlockData;
accessible	field	net/minecraft/server/PacketPlayOutPlayerListHeaderFooter	footer	Lnet/minecraft/server/IChatBaseComponent;
accessible	field	net/minecraft/server/PacketPlayOutPlayerListHeaderFooter	header	Lnet/minecraft/server/IChatBaseComponent;
accessible	field	net/minecraft/server/PacketPlayOutSpawnPosition	position	Lnet/minecraft/server/BlockPosition;
accessible	field	net/minecraft/server/PersistentRaid	raids	Ljava/util/Map;
accessible	field	net/minecraft/server/PlayerAbilities	flySpeed	F
accessible	field	net/minecraft/server/PlayerAbilities	walkSpeed	F
accessible	field	net/minecraft/server/PlayerChunk	oldTicketLevel	I
accessible	field	net/minecraft/server/PlayerChunk	players	Lnet/minecraft/server/PlayerChunk$d;
accessible	field	net/minecraft/server/PlayerChunkMap$EntityTracker	trackedPlayers	Ljava/util/Set;
accessible	field	net/minecraft/server/PlayerChunkMap	chunkDistanceManager	Lnet/minecraft/server/PlayerChunkMap$a;
accessible	field	net/minecraft/server/PlayerChunkMap	chunkGenerator	Lnet/minecraft/server/ChunkGenerator;
accessible	method	net/minecraft/server/PlayerChunkMap	saveChunk	(Lnet/minecraft/server/IChunkAccess;)Z
accessible	field	net/minecraft/server/PlayerChunkMap	trackedEntities	Lit/unimi/dsi/fastutil/ints/Int2ObjectMap;
accessible	field	net/minecraft/server/PlayerChunkMap	unloadQueue	Lit/unimi/dsi/fastutil/longs/LongSet;
accessible	field	net/minecraft/server/PlayerChunkMap	updatingChunks	Lit/unimi/dsi/fastutil/longs/Long2ObjectLinkedOpenHashMap;
accessible	field	net/minecraft/server/PlayerChunkMap	visibleChunks	Lit/unimi/dsi/fastutil/longs/Long2ObjectLinkedOpenHashMap;
accessible	field	net/minecraft/server/PlayerChunkMap	world	Lnet/minecraft/server/WorldServer;
accessible	field	net/minecraft/server/PlayerChunkMap	worldLoadListener	Lnet/minecraft/server/WorldLoadListener;
accessible	field	net/minecraft/server/PlayerList	playerFileData	Lnet/minecraft/server/IPlayerFileData;
accessible	field	net/minecraft/server/PlayerList	players	Ljava/util/List;
accessible	method	net/minecraft/server/PlayerList	sendScoreboard	(Lnet/minecraft/server/ScoreboardServer;Lnet/minecraft/server/EntityPlayer;)V
accessible	field	net/minecraft/server/PropertyManager	properties	Ljava/util/Properties;
accessible	field	net/minecraft/server/Raid	badOmenLevel	I
accessible	field	net/minecraft/server/Raid	heroes	Ljava/util/Set;
accessible	field	net/minecraft/server/Raid	numGroups	I
accessible	field	net/minecraft/server/Raid	ticksActive	J
accessible	field	net/minecraft/server/Raid	totalHealth	F
#accessible	method	net/minecraft/server/RecipeItemStack$StackProvider	<init>	(Lnet/minecraft/server/ItemStack;)V
#accessible	method	net/minecraft/server/RecipeItemStack	<init>	(Ljava/util/stream/Stream;)V
accessible	method	net/minecraft/server/RecipeItemStack	buildChoices	()V
accessible	field	net/minecraft/server/RecipeItemStack	choices	[Lnet/minecraft/server/ItemStack;
accessible	field	net/minecraft/server/RegionFileCache	cache	Lit/unimi/dsi/fastutil/longs/Long2ObjectLinkedOpenHashMap;
accessible	field	net/minecraft/server/ScoreboardObjective	displayName	Lnet/minecraft/server/IChatBaseComponent;
accessible	field	net/minecraft/server/Slot	index	I
accessible	field	net/minecraft/server/Ticket	identifier	Ljava/lang/Object;
accessible	field	net/minecraft/server/TileEntityBanner	color	Lnet/minecraft/server/EnumColor;
accessible	field	net/minecraft/server/TileEntityBanner	patterns	Lnet/minecraft/server/NBTTagList;
accessible	field	net/minecraft/server/TileEntityBeacon	chestLock	Lnet/minecraft/server/ChestLock;
accessible	field	net/minecraft/server/TileEntityBeacon	customName	Lnet/minecraft/server/IChatBaseComponent;
accessible	field	net/minecraft/server/TileEntityBeacon	levels	I
accessible	field	net/minecraft/server/TileEntityBeacon	primaryEffect	Lnet/minecraft/server/MobEffectList;
accessible	field	net/minecraft/server/TileEntityBeacon	secondaryEffect	Lnet/minecraft/server/MobEffectList;
accessible	field	net/minecraft/server/TileEntityBed	color	Lnet/minecraft/server/EnumColor;
accessible	field	net/minecraft/server/TileEntityBeehive	flowerPos	Lnet/minecraft/server/BlockPosition;
accessible	field	net/minecraft/server/TileEntityBrewingStand	brewTime	I
accessible	field	net/minecraft/server/TileEntityBrewingStand	fuelLevel	I
accessible	field	net/minecraft/server/TileEntityCampfire	cookingTimes	[I
accessible	field	net/minecraft/server/TileEntityCampfire	cookingTotalTimes	[I
accessible	field	net/minecraft/server/TileEntityContainer	chestLock	Lnet/minecraft/server/ChestLock;
accessible	field	net/minecraft/server/TileEntityContainer	customName	Lnet/minecraft/server/IChatBaseComponent;
accessible	field	net/minecraft/server/TileEntityEndGateway	age	J
accessible	field	net/minecraft/server/TileEntityEndGateway	exactTeleport	Z
accessible	field	net/minecraft/server/TileEntityEndGateway	exitPortal	Lnet/minecraft/server/BlockPosition;
accessible	field	net/minecraft/server/TileEntityFurnace	burnTime	I
accessible	field	net/minecraft/server/TileEntityFurnace	cookTime	I
accessible	field	net/minecraft/server/TileEntityFurnace	cookTimeTotal	I
accessible	field	net/minecraft/server/TileEntityLectern	inventory	Lnet/minecraft/server/IInventory;
accessible	method	net/minecraft/server/TileEntityLectern	setPage	(I)V
accessible	field	net/minecraft/server/TileEntityLootable	lootTable	Lnet/minecraft/server/MinecraftKey;
accessible	field	net/minecraft/server/TileEntityLootable	lootTableSeed	J
accessible	field	net/minecraft/server/TileEntitySign	isEditable	Z
accessible	field	net/minecraft/server/TileEntitySkull	gameProfile	Lcom/mojang/authlib/GameProfile;
accessible	field	net/minecraft/server/TileEntityStructure	author	Ljava/lang/String;
accessible	field	net/minecraft/server/TileEntityStructure	ignoreEntities	Z
accessible	field	net/minecraft/server/TileEntityStructure	integrity	F
accessible	field	net/minecraft/server/TileEntityStructure	metadata	Ljava/lang/String;
accessible	field	net/minecraft/server/TileEntityStructure	mirror	Lnet/minecraft/server/EnumBlockMirror;
accessible	field	net/minecraft/server/TileEntityStructure	relativePosition	Lnet/minecraft/server/BlockPosition;
accessible	field	net/minecraft/server/TileEntityStructure	rotation	Lnet/minecraft/server/EnumBlockRotation;
accessible	field	net/minecraft/server/TileEntityStructure	seed	J
accessible	field	net/minecraft/server/TileEntityStructure	showAir	Z
accessible	field	net/minecraft/server/TileEntityStructure	showBoundingBox	Z
accessible	field	net/minecraft/server/TileEntityStructure	size	Lnet/minecraft/server/BlockPosition;
accessible	field	net/minecraft/server/TileEntityStructure	usageMode	Lnet/minecraft/server/BlockPropertyStructureMode;
accessible	field	net/minecraft/server/World	serverThread	Ljava/lang/Thread;
accessible	field	net/minecraft/server/World	worldData	Lnet/minecraft/server/WorldData;
accessible	field	net/minecraft/server/WorldMap	humans	Ljava/util/Map;
accessible	field	net/minecraft/server/WorldPersistentData	data	Ljava/util/Map;
accessible	field	net/minecraft/server/WorldServer	entitiesById	Lit/unimi/dsi/fastutil/ints/Int2ObjectMap;
accessible	field	net/minecraft/server/Container	slots	Ljava/util/List;
mutable	field	net/minecraft/server/Container	slots	Ljava/util/List;
accessible	field	net/minecraft/server/CraftingManager	recipes	Ljava/util/Map;
mutable	field	net/minecraft/server/CraftingManager	recipes	Ljava/util/Map;
accessible	field	net/minecraft/server/DedicatedServer	propertyManager	Lnet/minecraft/server/DedicatedServerSettings;
mutable	field	net/minecraft/server/DedicatedServer	propertyManager	Lnet/minecraft/server/DedicatedServerSettings;
accessible	field	net/minecraft/server/EntityAreaEffectCloud	effects	Ljava/util/List;
mutable	field	net/minecraft/server/EntityAreaEffectCloud	effects	Ljava/util/List;
accessible	field	net/minecraft/server/EntityFishingHook	owner	Lnet/minecraft/server/EntityHuman;
mutable	field	net/minecraft/server/EntityFishingHook	owner	Lnet/minecraft/server/EntityHuman;
accessible	field	net/minecraft/server/EntityInsentient	goalSelector	Lnet/minecraft/server/PathfinderGoalSelector;
mutable	field	net/minecraft/server/EntityInsentient	goalSelector	Lnet/minecraft/server/PathfinderGoalSelector;
accessible	field	net/minecraft/server/EntityInsentient	targetSelector	Lnet/minecraft/server/PathfinderGoalSelector;
mutable	field	net/minecraft/server/EntityInsentient	targetSelector	Lnet/minecraft/server/PathfinderGoalSelector;
accessible	field	net/minecraft/server/EntityLiving	combatTracker	Lnet/minecraft/server/CombatTracker;
mutable	field	net/minecraft/server/EntityLiving	combatTracker	Lnet/minecraft/server/CombatTracker;
accessible	field	net/minecraft/server/EntityLiving	maxNoDamageTicks	I
mutable	field	net/minecraft/server/EntityLiving	maxNoDamageTicks	I
accessible	field	net/minecraft/server/ItemStack	item	Lnet/minecraft/server/Item;
mutable	field	net/minecraft/server/ItemStack	item	Lnet/minecraft/server/Item;
accessible	field	net/minecraft/server/MerchantRecipe	buyingItem1	Lnet/minecraft/server/ItemStack;
mutable	field	net/minecraft/server/MerchantRecipe	buyingItem1	Lnet/minecraft/server/ItemStack;
accessible	field	net/minecraft/server/MerchantRecipe	buyingItem2	Lnet/minecraft/server/ItemStack;
mutable	field	net/minecraft/server/MerchantRecipe	buyingItem2	Lnet/minecraft/server/ItemStack;
accessible	field	net/minecraft/server/MerchantRecipe	maxUses	I
mutable	field	net/minecraft/server/MerchantRecipe	maxUses	I
accessible	field	net/minecraft/server/MinecraftServer	commandDispatcher	Lnet/minecraft/server/CommandDispatcher;
mutable	field	net/minecraft/server/MinecraftServer	commandDispatcher	Lnet/minecraft/server/CommandDispatcher;
accessible	field	net/minecraft/server/MinecraftServer	convertable	Lnet/minecraft/server/Convertable;
mutable	field	net/minecraft/server/MinecraftServer	convertable	Lnet/minecraft/server/Convertable;
accessible	field	net/minecraft/server/MinecraftServer	serverConnection	Lnet/minecraft/server/ServerConnection;
mutable	field	net/minecraft/server/MinecraftServer	serverConnection	Lnet/minecraft/server/ServerConnection;
accessible	field	net/minecraft/server/MinecraftServer	universe	Ljava/io/File;
mutable	field	net/minecraft/server/MinecraftServer	universe	Ljava/io/File;
accessible	field	net/minecraft/server/TicketType	loadPeriod	J
mutable	field	net/minecraft/server/TicketType	loadPeriod	J
accessible	field	net/minecraft/server/World	worldProvider	Lnet/minecraft/server/WorldProvider;
mutable	field	net/minecraft/server/World	worldProvider	Lnet/minecraft/server/WorldProvider;
accessible	method	net/minecraft/server/StructureGenerator	getNearestGeneratedFeature	(Lnet/minecraft/server/World;Lnet/minecraft/server/ChunkGenerator;Lnet/minecraft/server/BlockPosition;IZ)Lnet/minecraft/server/BlockPosition;
